name = "newsnow"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "199c614c-f03f-4afe-8f28-eeedc1bc10d6"      # 替换为你创建的数据库 ID
